---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: flake8
        args:
          - --ignore=W605,W504,E722,F841,E501
  - repo: https://github.com/PyCQA/pylint.git
    rev: v3.2.2
    hooks:
      - id: pylint
        name: pylint (python 3)
        language_version: python3 #
        args:
          - --load-plugins=pylint.extensions.redefined_variable_type,pylint.extensions.bad_builtin
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
