---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-test-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-test-client
  template:
    metadata:
      labels:
        app: tcp-test-client
    spec:
      # hostNetwork: true
      containers:
        - name: tcp-test-client
          image: mikeage/tcp-test-client:v3
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST
              value: remote_target.address
