apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    appname: rmqtest
  name: rmqtest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: rmqtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: rmqtest
    spec:
      #hostNetwork: true
      containers:
      - image: europe-west2-docker.pkg.dev/hyperscale-dev2-vqhx/repository/rmqtest:v2
        imagePullPolicy: IfNotPresent
        name: rmqtest
        env:
        - name: RMQ_CONNECTION_STRING
          value: "amqp://USER:PASSWORD@HOST:5672"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
